var constants = module.exports = {
    START_SESSION_FROM_TASK: 'START_SESSION_FROM_TASK',
    NEW_SESSION: 'NEW_SESSION',
    COMPLETE_TASK: 'COMPLETE_TASK',
    ADD_TASK: 'ADD_TASK',
    UPDATE_TASK_TITLE: 'UPDATE_TASK_TITLE',
    UPDATE_TASK_DURATION: 'UPDATE_TASK_DURATION',
    DELETE_TASK: 'DELETE_TASK',
    USER_ACTION: 'USER_ACTION',
    USER_LEAVE: 'USER_LEAVE',
    CYCLE_NEWSFEED: 'CYCLE_NEWSFEED'
};
